SELECT * FROM [TABELA DE PRODUTOS]

--O comando CASE, ele vai me mostrar uma condição que, se satisfizer uma condição, faz uma coisa, se satisfizer outra condição, 
--vai fazer outra coisa e assim por diante até o final, onde eu posso colocar uma estrutura, que é o ELSE, que é como se fosse tudo que ele não classificou,
--o ELSE vai fazer.

SELECT [NOME DO PRODUTO],
CASE WHEN [PREÇO DE LISTA] >= 12 THEN 'PRODUTO CARO'
WHEN [PREÇO DE LISTA] >= 7 AND [PREÇO DE LISTA] < 12 THEN 'PRODUTO EM CONTA'
ELSE 'PRODUTO BARATO' END
FROM
[TABELA DE PRODUTOS]

SELECT [NOME DO PRODUTO],
CASE WHEN [PREÇO DE LISTA] >= 12 THEN 'PRODUTO CARO'
WHEN [PREÇO DE LISTA] >= 7 AND [PREÇO DE LISTA] < 12 THEN 'PRODUTO EM CONTA'
ELSE 'PRODUTO BARATO' END,
AVG([PREÇO DE LISTA])
FROM
[TABELA DE PRODUTOS]
GROUP BY [NOME DO PRODUTO],
CASE WHEN [PREÇO DE LISTA] >= 12 THEN 'PRODUTO CARO'
WHEN [PREÇO DE LISTA] >= 7 AND [PREÇO DE LISTA] < 12 THEN 'PRODUTO EM CONTA'
ELSE 'PRODUTO BARATO' END

SELECT YEAR(DATA), COUNT(*) FROM [NOTAS FISCAIS] GROUP BY YEAR(DATA)

SELECT NOME, [DATA DE NASCIMENTO], CASE WHEN YEAR([DATA DE NASCIMENTO]) < 1990 THEN 'ADULTOS'
WHEN YEAR([DATA DE NASCIMENTO]) BETWEEN 1990 AND 1995 THEN 'JOVENS'
ELSE 'CRIANÇAS' END AS [CLASSIFICAÇÃO ETÁRIA]
FROM [TABELA DE CLIENTES] 



