
SELECT * FROM [SUCOS_VENDAS].[DBO].[TABELA DE PRODUTOS] WHERE [CODIGO DO PRODUTO] = '1002334'

SELECT * FROM [PRODUTOS] WHERE [CÓDIGO] = '1002334'

SELECT B.[CODIGO DO PRODUTO], B.[PREÇO DE LISTA], A.[CÓDIGO], A.[PREÇO LISTA]
FROM [PRODUTOS] A INNER JOIN [SUCOS_VENDAS].[DBO].[TABELA DE PRODUTOS] B
ON A.[CÓDIGO] = B.[CODIGO DO PRODUTO]
WHERE [CÓDIGO] = '1002334'

UPDATE [SUCOS_VENDAS].[DBO].[TABELA DE PRODUTOS] SET [PREÇO DE LISTA] = 8
WHERE [CODIGO DO PRODUTO] = '1002334'

MERGE INTO [PRODUTOS] A --tabela destino
USING [SUCOS_VENDAS].[DBO].[TABELA DE PRODUTOS] B --tabela origem
ON A.[CÓDIGO] = B.[CODIGO DO PRODUTO] --condição
AND A.[CÓDIGO] = '1002334' --somente para
WHEN MATCHED THEN -- quando combinar
UPDATE SET A.[PREÇO LISTA] = B.[PREÇO DE LISTA]; --atualize

MERGE INTO CLIENTES A 
USING VENDEDORES B 
ON A.BAIRRO = B.BAIRRO
WHEN MATCHED THEN
UPDATE SET A.[VOLUME DE COMPRA] = A.[VOLUME DE COMPRA] * 1.30;


